---
name: CGI-Application-Plugin-Authentication
version: 0.04
author:
  - Cees Hek <ceeshek@gmail.com>
abstract: Authentication framework for CGI::Application
license: perl
requires:
  CGI::Application: 4
  Class::ISA: 0
  Scalar::Util: 0
  UNIVERSAL::require: 0
recommends:
  CGI::Application::Plugin::Session: 0
  CGI::Cookie: 0
  Digest::MD5: 0
  Digest::SHA1: 0
  MIME::Base64: 0
build_requires:
  Test::Exception: 0
  Test::More: 0
provides:
  CGI::Application::Plugin::Authentication:
    file: lib/CGI/Application/Plugin/Authentication.pm
    version: 0.04
  CGI::Application::Plugin::Authentication::Driver:
    file: lib/CGI/Application/Plugin/Authentication/Driver.pm
  CGI::Application::Plugin::Authentication::Driver::DBI:
    file: lib/CGI/Application/Plugin/Authentication/Driver/DBI.pm
  CGI::Application::Plugin::Authentication::Driver::Dummy:
    file: lib/CGI/Application/Plugin/Authentication/Driver/Dummy.pm
  CGI::Application::Plugin::Authentication::Driver::Filter::crypt:
    file: lib/CGI/Application/Plugin/Authentication/Driver/Filter/crypt.pm
  CGI::Application::Plugin::Authentication::Driver::Filter::lc:
    file: lib/CGI/Application/Plugin/Authentication/Driver/Filter/lc.pm
  CGI::Application::Plugin::Authentication::Driver::Filter::md5:
    file: lib/CGI/Application/Plugin/Authentication/Driver/Filter/md5.pm
  CGI::Application::Plugin::Authentication::Driver::Filter::sha1:
    file: lib/CGI/Application/Plugin/Authentication/Driver/Filter/sha1.pm
  CGI::Application::Plugin::Authentication::Driver::Filter::strip:
    file: lib/CGI/Application/Plugin/Authentication/Driver/Filter/strip.pm
  CGI::Application::Plugin::Authentication::Driver::Filter::uc:
    file: lib/CGI/Application/Plugin/Authentication/Driver/Filter/uc.pm
  CGI::Application::Plugin::Authentication::Driver::Generic:
    file: lib/CGI/Application/Plugin/Authentication/Driver/Generic.pm
  CGI::Application::Plugin::Authentication::Store:
    file: lib/CGI/Application/Plugin/Authentication/Store.pm
  CGI::Application::Plugin::Authentication::Store::Cookie:
    file: lib/CGI/Application/Plugin/Authentication/Store/Cookie.pm
  CGI::Application::Plugin::Authentication::Store::Session:
    file: lib/CGI/Application/Plugin/Authentication/Store/Session.pm
generated_by: Module::Build version 0.2611
